### ISSUE TITLE
put in the back, but not close

### ISSUE THREAD

**Issue by aurelien-git** [moll/vim-bbye#2]
Hello moll!

When I :Bdelete on a buffer, it put the buffer in the back, give me another buffer, but a CTRL-o give me the buffer back.

**Comment by moll** [comment]
Hey!

Indeed. I've noticed this too, so thanks for the bump. Quite annoying, isn't it? ^_^ You wouldn't happen to know how to quickly solve this, would you? :-)

**Comment by 4ur3l13n** [comment]
I am really noob on Vim something like two weeks ... but I can try to have a look on the code to try to help you to find the way to make it works.

**Comment by tssund93** [comment]
I know this is old, but that's a feature of Vim.  When a buffer is deleted, it's unloaded from RAM, but its jumplist is preserved, so you can still jump back to it with Ctrl-O and it will be reloaded.  Changing this in the plugin would break consistency with the actually :bdelete command.  Just my two cents.

**Comment by moll** [comment]
Thanks for pointing that out, @tssund93. Perhaps Bbye.vim could use a Bwipeout, too, for @aurelien-git's case. Or did `:bwipeout` behave like `:bdelete` when it came to jumping back?

**Comment by tssund93** [comment]
`:bwipeout` does delete entries in the jumplist related to the file (and every other stored thing related to the file), so a `:Bwipeout` command would be what @aurelien-git would want.

**Comment by moll** [comment]
@juanibiapina helped out and added `:Bwipeout`. Grab the latest master, fellows, to give it a try.
