### ISSUE TITLE
E516: No buffers were deleted: bdelete

### ISSUE THREAD

**Issue by QMonkey** [moll/vim-bbye#5]
When I use Bdelete command to delete [fugitive](https://github.com/tpope/vim-fugitive)'s Glog buffer, the buffer is successfully deleted, but I get the error below.

```
Error detected while processing function <SNR>87_bdelete:
E516: No buffers were deleted: bdelete 6
```

The buffer number of Glog is 6..

**Comment by moll** [comment]
Thanks for reporting! I've seen this too. Should really investigate. :)

**Comment by simonsmith** [comment]
I presume this is related, but if I try to close a buffer from `:Gblame` I also see:

```
Error detected while processing function <SNR>48_bdelete:
line   45:
E516: No buffers were deleted: bdelete 7
Press ENTER or type command to continue
```

After pressing Enter the buffer closes as expected

**Comment by samuelsimoes** [comment]
The problem seems to happen when you try close a buffer with:

`setlocal bufhidden=delete`

**Comment by moll** [comment]
Thank you all for your help! I've switched `bufexists()` to `buflisted()` to counter `bufhidden=delete`. I guess the plugins I tested originally all used `bufhidden=wipe` so I didn't think how deleting a deleted buffer would work. :)
